// <auto-generated />
using System;
using LearningDocumentSystem.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningDocumentSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715125326_AddPackagePlans")]
    partial class AddPackagePlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.AllowedEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AllowedEmails", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChapterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterID"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("ChapterID");

                    b.HasIndex("SubjectID")
                        .HasDatabaseName("IX_Chapters_SubjectID");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<double?>("ExecutionTimeMs")
                        .HasColumnType("float");

                    b.Property<int?>("Feedback")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageID");

                    b.HasIndex("SessionID")
                        .HasDatabaseName("IX_ChatMessages_SessionID");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.ChatSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SessionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ChatSessions_UpdatedAt");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IX_ChatSessions_UserID");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<int>("ChapterID")
                        .HasColumnType("int");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IndexStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("ChapterID")
                        .HasDatabaseName("IX_Documents_ChapterID");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("IX_Documents_FileHash");

                    b.HasIndex("OriginalFileName")
                        .IsUnique()
                        .HasDatabaseName("IX_Documents_OriginalFileName");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("IX_Documents_UploadedBy");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.DocumentChunk", b =>
                {
                    b.Property<int>("ChunkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChunkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChunkID"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.HasKey("ChunkID");

                    b.HasIndex("DocumentID")
                        .HasDatabaseName("IX_Chunks_DocumentID");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.DocumentConflict", b =>
                {
                    b.Property<int>("ConflictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConflictID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConflictID"));

                    b.Property<int>("ChunkID")
                        .HasColumnType("int");

                    b.Property<int>("ConflictingChunkID")
                        .HasColumnType("int");

                    b.Property<int>("ConflictingDocumentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.HasKey("ConflictID");

                    b.HasIndex("ChunkID");

                    b.HasIndex("ConflictingChunkID");

                    b.HasIndex("ConflictingDocumentID")
                        .HasDatabaseName("IX_DocumentConflicts_ConflictingDocumentID");

                    b.HasIndex("DocumentID")
                        .HasDatabaseName("IX_DocumentConflicts_DocumentID");

                    b.ToTable("DocumentConflicts", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Embedding", b =>
                {
                    b.Property<int>("EmbeddingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmbeddingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmbeddingID"));

                    b.Property<int>("ChunkID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("VectorData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmbeddingID");

                    b.HasIndex("ChunkID")
                        .IsUnique();

                    b.ToTable("Embeddings", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.PackagePlan", b =>
                {
                    b.Property<int>("PackagePlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PackagePlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackagePlanID"));

                    b.Property<string>("AllowedProvidersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DailyMessageLimit")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PackagePlanID");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PackagePlans_Code");

                    b.ToTable("PackagePlans", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTransactions_TransactionReference");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IX_PaymentTransactions_UserID");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubjectLeaderID")
                        .HasColumnType("int")
                        .HasColumnName("SubjectLeaderID");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SubjectID");

                    b.HasIndex("SubjectCode")
                        .IsUnique();

                    b.HasIndex("SubjectLeaderID");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.SystemChunkSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChunkOverlap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("ChunkSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(800);

                    b.Property<int>("MinChunkLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Recursive");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserId");

                    b.ToTable("SystemChunkSettings", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("CanUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IX_UserRoles_UserID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Chapter", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.ChatMessage", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.ChatSession", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Document", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningDocumentSystem.Entities.Models.User", "UploadedByUser")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.DocumentChunk", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.DocumentConflict", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.DocumentChunk", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningDocumentSystem.Entities.Models.DocumentChunk", "ConflictingChunk")
                        .WithMany()
                        .HasForeignKey("ConflictingChunkID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningDocumentSystem.Entities.Models.Document", "ConflictingDocument")
                        .WithMany()
                        .HasForeignKey("ConflictingDocumentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningDocumentSystem.Entities.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("ConflictingChunk");

                    b.Navigation("ConflictingDocument");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Embedding", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.DocumentChunk", "Chunk")
                        .WithOne("Embedding")
                        .HasForeignKey("LearningDocumentSystem.Entities.Models.Embedding", "ChunkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.PaymentTransaction", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Subject", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.User", "SubjectLeader")
                        .WithMany()
                        .HasForeignKey("SubjectLeaderID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubjectLeader");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.SystemChunkSetting", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("LearningDocumentSystem.Entities.Models.SystemChunkSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.UserRole", b =>
                {
                    b.HasOne("LearningDocumentSystem.Entities.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningDocumentSystem.Entities.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.DocumentChunk", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("LearningDocumentSystem.Entities.Models.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Documents");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
